name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BASE_IMAGE_VERSION: "3.8-alpine3.11"
      POETRY_VERSION: "1.0.2"
      TAG: "python3.8-poetry1.0"

      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: moneymeets/ruby-python-awscli

    steps:
      - uses: actions/checkout@v1

      - name: Build and publish image
        run: |
          # For branch names other than master (e.g. feature/test), append last branch name component (test) to the tag
          if [ "$GITHUB_REF" != "refs/heads/master" ]; then export TAG=$TAG-${GITHUB_REF##*/} ; fi
          export IMAGE=$DOCKER_REGISTRY:$TAG
          docker build --build-arg BASE_IMAGE_VERSION=$BASE_IMAGE_VERSION --build-arg POETRY_VERSION=$POETRY_VERSION -t $IMAGE .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE
